version: '3.3'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: trains-schedule
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Test1234
    ports:
      - "5432:5432"
    # volumes:
    # - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

  backend:
    build:
      context: ./backend
    environment:
      - PORT=5002
      - POSTGRES_HOST=trains-schedule.ch0yu4o08sb6.eu-north-1.rds.amazonaws.com
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRESS_PASSWORD=Test1234
      - POSTGRES_PORT=5432
    ports:
      - "5002:5002"
    depends_on:
      - db
    volumes:
      - ./backend:/app
